DROP TABLE IF EXISTS school CASCADE;
-- Create School Table
-- Assume Person '1' did all the entries
CREATE TABLE school (
   id serial PRIMARY KEY,
   name VARCHAR(50) NOT NULL,
   description VARCHAR(32000) NOT NULL,
   location VARCHAR(50) NOT NULL,
   country VARCHAR(50) NOT NULL,
   responsibleId INT NOT NULL,
   status VARCHAR(50) NOT NULL,
   deploymentDate DATE NOT NULL,
   tabletType VARCHAR(50),
   numDoodleStudents INT,
   internetDetails VARCHAR(50),
   totalSchools INT,
   created_ById INT NOT NULL,
   created_At TIMESTAMP NOT NULL DEFAULT NOW(),
   FOREIGN KEY (responsibleId)
                             REFERENCES person (id),
   FOREIGN KEY (created_ById)
                             REFERENCES person (id));

-- Mock Data - ensure 'person' database exist

INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Yundt LLC', 'Cape First', 
                                  'Indonesia',
                                  1, 'Autonomous', 
                                  '2020-09-04 20:38:22',
                                  'Lenovo',
                                  74,
                                  'Strong Wifi',
                                  5,
                                  'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Roob, Legros and Kozey', 'Gerald', 
                                  'Philippines',
                                  1, 'Autonomous', 
                                  '2018-04-24 04:09:39',
                                  'Lenovo',
                                  18,
                                  'None',
                                  6,
                                  'Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Bins-Konopelski', 'Valley Edge', 
                                  'Philippines',
                                  1, 'Autonomous', 
                                  '2017-12-27 11:57:19',
                                  'Nexus',
                                  96,
                                  'Spotty Wifi',
                                  9,
                                  'In quis justo.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Hagenes, Bosco and Morar', 'Nova', 
                                  'Greece',
                                  1, 'Autonomous', 
                                  '2017-05-12 08:44:53',
                                  'Lenovo',
                                  51,
                                  'BF Router',
                                  10,
                                  'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Bergnaum-Kuhn', 'Buell', 
                                  'China',
                                  1, 'Autonomous', 
                                  '2017-10-26 23:14:42',
                                  'Ipad',
                                  37,
                                  'WCED Wifi',
                                  6,
                                  'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti. Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Nicolas-Ferry', 'Westerfield', 
                                  'Ukraine',
                                  1, 'Autonomous', 
                                  '2017-10-23 02:54:48',
                                  'Ipad',
                                  72,
                                  'WCED Wifi',
                                  1,
                                  'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus. Phasellus in felis.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Connelly Inc', 'Gina', 
                                  'Sweden',
                                  1, 'Autonomous', 
                                  '2019-03-17 18:28:56',
                                  'Ipad',
                                  93,
                                  'Spotty Wifi',
                                  8,
                                  'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Hermiston, Lockman and Rohan', 'Spenser', 
                                  'France',
                                  1, 'Autonomous', 
                                  '2021-04-20 23:17:20',
                                  'Lenovo',
                                  62,
                                  'None',
                                  10,
                                  'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat. Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Kon, Conroy and Grant', 'Prairieview', 
                                  'Poland',
                                  1, 'Autonomous', 
                                  '2018-11-26 21:04:17',
                                  'Lenovo',
                                  10,
                                  'WCED Wifi',
                                  3,
                                  'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Gutmann Inc', 'Steensland', 
                                  'China',
                                  1, 'Autonomous', 
                                  '2021-11-15 10:47:03',
                                  'Lenovo',
                                  53,
                                  'Spotty Wifi',
                                  3,
                                  'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Schoen Inc', 'Vidon', 
                                  'Netherlands',
                                  1, 'Autonomous', 
                                  '2017-02-05 19:42:52',
                                  'Lenovo',
                                  3,
                                  'BF Router',
                                  10,
                                  'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Sanford Group', 'Lotheville', 
                                  'Albania',
                                  1, 'Autonomous', 
                                  '2021-12-22 16:04:55',
                                  'Ipad',
                                  36,
                                  'Strong Wifi',
                                  5,
                                  'Nunc rhoncus dui vel sem. Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus. Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Wyman-Boyle', 'Susan', 
                                  'Sweden',
                                  1, 'Autonomous', 
                                  '2019-07-29 18:15:36',
                                  'Nexus',
                                  37,
                                  'Strong Wifi',
                                  9,
                                  'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat. In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Yundt-Abbott', 'Corben', 
                                  'Argentina',
                                  1, 'Autonomous', 
                                  '2021-07-30 13:56:05',
                                  'Nexus',
                                  24,
                                  'None',
                                  5,
                                  'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Jenkins, Mante and Bartoletti', 'Kensington', 
                                  'Colombia',
                                  1, 'Autonomous', 
                                  '2017-08-12 00:48:46',
                                  'Nexus',
                                  70,
                                  'None',
                                  1,
                                  'Vivamus vestibulum sagittis sapien.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Gutmann LLC', 'Hooker', 
                                  'Colombia',
                                  1, 'Autonomous', 
                                  '2018-05-22 01:13:29',
                                  'Nexus',
                                  0,
                                  'WCED Wifi',
                                  1,
                                  'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Auer-Legros', 'Anthes', 
                                  'New Zealand',
                                  1, 'Autonomous', 
                                  '2019-07-31 14:44:32',
                                  'Ipad',
                                  84,
                                  'Spotty Wifi',
                                  4,
                                  'Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Medhurst-McLaughlin', 'Maywood', 
                                  'China',
                                  1, 'Autonomous', 
                                  '2022-04-25 13:55:12',
                                  'Lenovo',
                                  20,
                                  'BF Router',
                                  4,
                                  'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('McKenzie, Schmidt and Connell', 'Corry', 
                                  'Colombia',
                                  1, 'Autonomous', 
                                  '2021-06-18 14:09:51',
                                  'Nexus',
                                  8,
                                  'WCED Wifi',
                                  10,
                                  'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Blick, Sauer and Stamm', 'Stang', 
                                  'China',
                                  1, 'Autonomous', 
                                  '2019-06-28 16:22:52',
                                  'Nexus',
                                  60,
                                  'WCED Wifi',
                                  2,
                                  'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Moen, Cummerata and Mayer', 'Moose', 
                                  'China',
                                  1, 'Autonomous', 
                                  '2019-11-15 10:12:23',
                                  'Ipad',
                                  13,
                                  'Spotty Wifi',
                                  5,
                                  'Aliquam quis turpis eget elit sodales scelerisque.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Kub LLC', 'Stuart', 
                                  'Philippines',
                                  1, 'Autonomous', 
                                  '2019-07-10 00:58:29',
                                  'Lenovo',
                                  56,
                                  'WCED Wifi',
                                  5,
                                  'Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Konopelski-Beer', 'Donald', 
                                  'China',
                                  1, 'Autonomous', 
                                  '2021-12-04 03:56:53',
                                  'Lenovo',
                                  84,
                                  'Strong Wifi',
                                  1,
                                  'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Wiza, Ziemann and Kon', 'Sycamore', 
                                  'Portugal',
                                  1, 'Autonomous', 
                                  '2018-10-09 04:17:18',
                                  'Lenovo',
                                  78,
                                  'Strong Wifi',
                                  5,
                                  'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Hansen, Hane and Bayer', 'Dayton', 
                                  'Democratic Republic of the Congo',
                                  1, 'Autonomous', 
                                  '2017-11-18 04:55:14',
                                  'Nexus',
                                  45,
                                  'Strong Wifi',
                                  9,
                                  'Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Hudson and Sons', 'Upham', 
                                  'Russia',
                                  1, 'Autonomous', 
                                  '2018-02-11 01:41:22',
                                  'Ipad',
                                  10,
                                  'Strong Wifi',
                                  6,
                                  'Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Moore Group', 'Carpenter', 
                                  'China',
                                  1, 'Autonomous', 
                                  '2018-09-27 02:16:08',
                                  'Nexus',
                                  79,
                                  'Spotty Wifi',
                                  5,
                                  'Etiam faucibus cursus urna. Ut tellus. Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi. Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Turcotte, Pfeffer and Feeney', 'Sage', 
                                  'Myanmar',
                                  1, 'Autonomous', 
                                  '2019-10-14 16:33:45',
                                  'Lenovo',
                                  17,
                                  'Spotty Wifi',
                                  5,
                                  'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat. Nulla nisl. Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Boyer-Runte', 'Haas', 
                                  'China',
                                  1, 'Autonomous', 
                                  '2020-03-14 19:07:10',
                                  'Ipad',
                                  84,
                                  'Strong Wifi',
                                  5,
                                  'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Kozey, Mueller and Kerluke', 'Ronald Regan', 
                                  'Japan',
                                  1, 'Autonomous', 
                                  '2020-12-26 21:08:16',
                                  'Ipad',
                                  48,
                                  'Spotty Wifi',
                                  3,
                                  'Duis mattis egestas metus. Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Schultz-Witting', 'Pierstorff', 
                                  'China',
                                  1, 'Autonomous', 
                                  '2016-11-20 18:56:21',
                                  'Lenovo',
                                  23,
                                  'WCED Wifi',
                                  3,
                                  'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh. In quis justo.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Hilll-Mohr', 'Bluejay', 
                                  'Greece',
                                  1, 'Autonomous', 
                                  '2017-12-30 17:31:53',
                                  'Nexus',
                                  45,
                                  'WCED Wifi',
                                  6,
                                  'Donec dapibus. Duis at velit eu est congue elementum. In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo. Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Howe Inc', 'Bashford', 
                                  'Indonesia',
                                  1, 'Autonomous', 
                                  '2019-02-25 20:44:25',
                                  'Nexus',
                                  94,
                                  'Strong Wifi',
                                  6,
                                  'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat. Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Berge, Treutel and Schmidt', 'Doe Crossing', 
                                  'Russia',
                                  1, 'Autonomous', 
                                  '2017-02-21 12:27:37',
                                  'Nexus',
                                  38,
                                  'Strong Wifi',
                                  10,
                                  'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Price, Lakin and Streich', 'Clove', 
                                  'Brazil',
                                  1, 'Autonomous', 
                                  '2019-05-27 02:53:04',
                                  'Lenovo',
                                  72,
                                  'WCED Wifi',
                                  6,
                                  'Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Veum-Heathcote', 'Monument', 
                                  'Poland',
                                  1, 'Autonomous', 
                                  '2019-11-29 05:14:42',
                                  'Ipad',
                                  87,
                                  'Spotty Wifi',
                                  5,
                                  'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Weimann Group', 'Burning Wood', 
                                  'Bulgaria',
                                  1, 'Autonomous', 
                                  '2020-04-07 10:28:50',
                                  'Nexus',
                                  24,
                                  'WCED Wifi',
                                  6,
                                  'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Monahan, Witting and Keefe', 'Forest Run', 
                                  'France',
                                  1, 'Autonomous', 
                                  '2017-03-24 01:18:24',
                                  'Lenovo',
                                  13,
                                  'Strong Wifi',
                                  9,
                                  'In congue. Etiam justo. Etiam pretium iaculis justo. In hac habitasse platea dictumst.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Rowe-McClure', 'Union', 
                                  'Czech Republic',
                                  1, 'Autonomous', 
                                  '2021-03-09 02:02:45',
                                  'Ipad',
                                  41,
                                  'None',
                                  1,
                                  'Proin risus. Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Hermann, Gislason and Carroll', 'Shoshone', 
                                  'Nigeria',
                                  1, 'Autonomous', 
                                  '2017-06-03 16:28:46',
                                  'Ipad',
                                  23,
                                  'WCED Wifi',
                                  9,
                                  'In hac habitasse platea dictumst.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Jast and Sons', 'Hagan', 
                                  'Sri Lanka',
                                  1, 'Autonomous', 
                                  '2020-11-18 06:33:45',
                                  'Ipad',
                                  78,
                                  'Strong Wifi',
                                  7,
                                  'Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Nitzsche, Mertz and West', 'Arrowood', 
                                  'Australia',
                                  1, 'Autonomous', 
                                  '2019-12-29 16:19:45',
                                  'Lenovo',
                                  9,
                                  'Spotty Wifi',
                                  9,
                                  'Nunc purus. Phasellus in felis. Donec semper sapien a libero. Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius. Integer ac leo.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Towne, Schaden and Ankunding', 'Golden Leaf', 
                                  'China',
                                  1, 'Autonomous', 
                                  '2019-11-15 11:47:35',
                                  'Lenovo',
                                  8,
                                  'WCED Wifi',
                                  4,
                                  'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Schulist Group', 'Steensland', 
                                  'China',
                                  1, 'Autonomous', 
                                  '2020-05-30 22:26:19',
                                  'Nexus',
                                  42,
                                  'Spotty Wifi',
                                  7,
                                  'Morbi non quam nec dui luctus rutrum. Nulla tellus.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Stroman Inc', 'Heath', 
                                  'China',
                                  1, 'Autonomous', 
                                  '2017-08-25 01:13:36',
                                  'Nexus',
                                  5,
                                  'None',
                                  6,
                                  'Proin at turpis a pede posuere nonummy. Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque. Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Heathcote Inc', 'Tennyson', 
                                  'Greece',
                                  1, 'Autonomous', 
                                  '2021-07-02 12:27:10',
                                  'Lenovo',
                                  96,
                                  'WCED Wifi',
                                  10,
                                  'Suspendisse accumsan tortor quis turpis.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Kon-Lakin', 'Waubesa', 
                                  'Ecuador',
                                  1, 'Autonomous', 
                                  '2021-05-24 09:12:01',
                                  'Ipad',
                                  36,
                                  'None',
                                  6,
                                  'Aliquam erat volutpat. In congue.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Schiller-Graham', 'Kingsford', 
                                  'Japan',
                                  1, 'Autonomous', 
                                  '2020-01-20 10:16:46',
                                  'Nexus',
                                  90,
                                  'WCED Wifi',
                                  9,
                                  'Ut at dolor quis odio consequat varius. Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Stoltenberg, Feest and Renner', 'Pine View', 
                                  'Argentina',
                                  1, 'Autonomous', 
                                  '2018-08-17 06:08:36',
                                  'Nexus',
                                  48,
                                  'BF Router',
                                  1,
                                  'Proin interdum mauris non ligula pellentesque ultrices.',
                                  1);
INSERT INTO school (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, description,
                                  created_ById)
        VALUES ('Hauck-Stracke', 'American Ash', 
                                  'Indonesia',
                                  1, 'Autonomous', 
                                  '2018-09-27 19:03:56',
                                  'Ipad',
                                  54,
                                  'None',
                                  7,
                                  'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.',
                                  1);
