
-- Create Schedule Tracker Table
CREATE TABLE scheduletracker (
   id serial PRIMARY KEY,
   surveyDate DATE NOT NULL,
   schoolId INT NOT NULL,
   deliveredById INT NOT NULL,
   duration INT NOT NULL,
   briefSummary VARCHAR(50) NOT NULL,
   numOfStaff INT NOT NULL,
   numOfStudents INT NOT NULL,
   supportCategory VARCHAR(50) NOT NULL,
   programmeInitiativeId INT NOT NULL,
   supportType VARCHAR(50) NOT NULL,
   createdById INT NOT NULL,
   createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
   FOREIGN KEY (deliveredById)
                             REFERENCES users (id),
   FOREIGN KEY (schoolId)
                             REFERENCES schoolstat (id),
   FOREIGN KEY (programmeInitiativeId)
                             REFERENCES initiative (id));

-- Mock Data - ensure 'person, schoolstat, initiative' databases exist

INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2016-12-19 11:22:31', 
                                15,10,
                                4.5, 
                                'Health Care',
                                14, 
                                14, 
                                'LDA',
                                'Internal Work', 
                                18,
                                15);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2019-04-23 00:22:51', 
                                1,7,
                                4.5, 
                                'Vusa Training',
                                9, 
                                7, 
                                'Visual Basic',
                                'Internal Work', 
                                7,
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2018-09-20 03:59:31', 
                                14,3,
                                2, 
                                'Miscellaneous',
                                1, 
                                13, 
                                'Adult Education',
                                'Internal Work', 
                                11,
                                14);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2019-08-18 09:23:29', 
                                15,17,
                                4.5, 
                                'Vusa Training',
                                9, 
                                6, 
                                'Google Docs',
                                'Direct Work', 
                                6,
                                15);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2016-12-14 23:19:33', 
                                8,15,
                                1.5, 
                                'Finance',
                                2, 
                                18, 
                                'Vector Illustration',
                                'Internal Work', 
                                4,
                                8);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2021-12-15 16:57:54', 
                                17,2,
                                1.5, 
                                'Finance',
                                18, 
                                17, 
                                'RNAi',
                                'Direct Work', 
                                13,
                                17);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2016-11-10 03:08:44', 
                                6,13,
                                4.5, 
                                'Finance',
                                16, 
                                13, 
                                'Twill',
                                'Internal Work', 
                                18,
                                6);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2022-04-04 14:23:06', 
                                9,19,
                                5, 
                                'Consumer Services',
                                7, 
                                11, 
                                'SMO',
                                'Direct Work', 
                                16,
                                9);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2016-08-05 18:32:07', 
                                8,12,
                                3, 
                                'Consumer Non-Durables',
                                8, 
                                8, 
                                'Digital Illustration',
                                'Internal Work', 
                                8,
                                8);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2018-03-20 21:40:00', 
                                12,12,
                                6, 
                                'Vusa Training',
                                12, 
                                10, 
                                'RMS',
                                'Direct Work', 
                                4,
                                12);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2018-12-25 10:03:07', 
                                20,6,
                                2, 
                                'Finance',
                                13, 
                                4, 
                                'Zsh',
                                'Internal Work', 
                                14,
                                20);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2021-02-25 23:35:37', 
                                5,2,
                                4.5, 
                                'Consumer Non-Durables',
                                10, 
                                18, 
                                'TSM Administration',
                                'Direct Work', 
                                10,
                                5);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2019-02-15 18:48:18', 
                                18,18,
                                3.5, 
                                'Vusa Training',
                                9, 
                                6, 
                                'XStream',
                                'Direct Work', 
                                4,
                                18);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2019-02-24 11:57:56', 
                                20,19,
                                2.5, 
                                'Vusa Training',
                                19, 
                                10, 
                                'D3.js',
                                'Direct Work', 
                                17,
                                20);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2017-03-26 21:48:18', 
                                19,3,
                                1, 
                                'Vusa Training',
                                10, 
                                6, 
                                'ISO 27001',
                                'Internal Work', 
                                8,
                                19);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2019-04-06 21:39:31', 
                                2,1,
                                2, 
                                'Vusa Training',
                                10, 
                                14, 
                                'Analog Circuit Design',
                                'Direct Work', 
                                13,
                                2);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2020-04-10 05:29:46', 
                                19,11,
                                5.5, 
                                'Consumer Services',
                                1, 
                                16, 
                                'Yeast two-hybrid',
                                'Internal Work', 
                                10,
                                19);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2016-07-17 07:30:57', 
                                8,9,
                                5.5, 
                                'Consumer Services',
                                3, 
                                5, 
                                'Web Typography',
                                'Direct Work', 
                                3,
                                8);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2020-08-18 06:12:01', 
                                2,8,
                                3.5, 
                                'Public Utilities',
                                3, 
                                10, 
                                'Type Rating',
                                'Direct Work', 
                                11,
                                2);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2018-06-09 21:48:52', 
                                9,2,
                                3, 
                                'Capital Goods',
                                6, 
                                2, 
                                'Bash',
                                'Direct Work', 
                                2,
                                9);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2022-03-21 12:21:43', 
                                15,16,
                                5.5, 
                                'Miscellaneous',
                                14, 
                                17, 
                                'MDX',
                                'Internal Work', 
                                15,
                                15);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2020-12-19 12:59:32', 
                                19,20,
                                2.5, 
                                'Consumer Non-Durables',
                                1, 
                                20, 
                                'QAM',
                                'Internal Work', 
                                11,
                                19);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2022-04-29 01:59:16', 
                                20,2,
                                4, 
                                'Vusa Training',
                                10, 
                                15, 
                                'Kitchen Remodeling',
                                'Direct Work', 
                                5,
                                20);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2017-09-13 08:45:06', 
                                12,16,
                                2, 
                                'Consumer Services',
                                16, 
                                11, 
                                'GMDSS',
                                'Direct Work', 
                                7,
                                12);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2018-03-19 11:27:10', 
                                8,4,
                                2, 
                                'Finance',
                                4, 
                                20, 
                                'DFR',
                                'Direct Work', 
                                10,
                                8);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2019-12-09 16:47:38', 
                                13,7,
                                4.5, 
                                'Consumer Non-Durables',
                                2, 
                                18, 
                                'OA Framework',
                                'Internal Work', 
                                7,
                                13);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2019-11-13 11:51:47', 
                                2,16,
                                4, 
                                'Vusa Training',
                                20, 
                                19, 
                                'Egyptian Arabic',
                                'Internal Work', 
                                18,
                                2);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2021-05-09 08:00:10', 
                                9,14,
                                2.5, 
                                'Vusa Training',
                                1, 
                                6, 
                                'JBoss Application Server',
                                'Internal Work', 
                                5,
                                9);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2019-03-23 14:52:25', 
                                6,5,
                                4.5, 
                                'Vusa Training',
                                5, 
                                1, 
                                'Vaccines',
                                'Internal Work', 
                                14,
                                6);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2022-06-05 16:44:52', 
                                7,18,
                                2.5, 
                                'Consumer Services',
                                2, 
                                12, 
                                'Kronos',
                                'Internal Work', 
                                6,
                                7);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2017-04-27 22:17:39', 
                                8,5,
                                1.5, 
                                'Energy',
                                4, 
                                19, 
                                'High Yield Bonds',
                                'Internal Work', 
                                16,
                                8);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2019-10-18 06:47:10', 
                                11,6,
                                3, 
                                'Capital Goods',
                                7, 
                                0, 
                                'Waterfront',
                                'Direct Work', 
                                16,
                                11);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2020-01-13 16:57:54', 
                                13,19,
                                3, 
                                'Vusa Training',
                                17, 
                                0, 
                                'BOSIET',
                                'Direct Work', 
                                9,
                                13);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2021-03-09 15:17:09', 
                                4,15,
                                3.5, 
                                'Vusa Training',
                                12, 
                                17, 
                                'XML Sitemaps',
                                'Internal Work', 
                                12,
                                4);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2021-12-07 21:54:23', 
                                5,2,
                                2.5, 
                                'Consumer Non-Durables',
                                9, 
                                11, 
                                'LP',
                                'Direct Work', 
                                2,
                                5);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2017-10-16 11:44:13', 
                                12,16,
                                2, 
                                'Consumer Services',
                                1, 
                                8, 
                                'MRIS',
                                'Internal Work', 
                                15,
                                12);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2017-05-20 05:26:02', 
                                15,19,
                                5, 
                                'Finance',
                                12, 
                                5, 
                                'Epi Info',
                                'Direct Work', 
                                16,
                                15);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2019-05-16 16:08:55', 
                                20,4,
                                1, 
                                'Basic Industries',
                                13, 
                                5, 
                                'UCSC Genome Browser',
                                'Internal Work', 
                                11,
                                20);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2017-11-30 09:17:57', 
                                3,15,
                                5.5, 
                                'Vusa Training',
                                2, 
                                16, 
                                'RS Means',
                                'Internal Work', 
                                18,
                                3);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2017-06-10 15:08:18', 
                                20,11,
                                4, 
                                'Finance',
                                7, 
                                1, 
                                'KOL Identification',
                                'Internal Work', 
                                12,
                                20);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2017-01-24 08:56:40', 
                                18,18,
                                3, 
                                'Miscellaneous',
                                15, 
                                16, 
                                'Customer Support',
                                'Internal Work', 
                                3,
                                18);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2022-06-03 12:40:18', 
                                9,13,
                                1.5, 
                                'Finance',
                                4, 
                                0, 
                                'IEEE standards',
                                'Direct Work', 
                                12,
                                9);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2020-08-20 06:07:10', 
                                4,1,
                                2, 
                                'Miscellaneous',
                                15, 
                                4, 
                                'Kyphoplasty',
                                'Internal Work', 
                                16,
                                4);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2018-01-30 12:20:47', 
                                7,10,
                                5.5, 
                                'Health Care',
                                6, 
                                2, 
                                'Dynamic Speaker',
                                'Internal Work', 
                                4,
                                7);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2019-01-31 13:58:58', 
                                9,4,
                                5, 
                                'Consumer Services',
                                1, 
                                16, 
                                'Title Searches',
                                'Internal Work', 
                                1,
                                9);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2017-07-27 02:26:31', 
                                4,17,
                                4, 
                                'Finance',
                                10, 
                                10, 
                                'Blues',
                                'Direct Work', 
                                7,
                                4);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2021-05-21 04:07:27', 
                                18,12,
                                1, 
                                'Vusa Training',
                                8, 
                                1, 
                                'Dreamweaver',
                                'Direct Work', 
                                4,
                                18);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2020-10-30 21:06:02', 
                                12,11,
                                5.5, 
                                'Basic Industries',
                                1, 
                                1, 
                                'FHA',
                                'Internal Work', 
                                10,
                                12);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2018-01-02 12:10:18', 
                                11,13,
                                3, 
                                'Vusa Training',
                                2, 
                                17, 
                                'VC-1',
                                'Direct Work', 
                                3,
                                11);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfStaff, numOfStudents,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          createdById)
        VALUES ('2016-08-01 17:46:50', 
                                3,6,
                                3, 
                                'Health Care',
                                5, 
                                13, 
                                'Eyelid Surgery',
                                'Direct Work', 
                                8,
                                3);
