DROP TABLE IF EXISTS scheduletracker;
-- Create Schedule Tracker Table
CREATE TABLE scheduletracker (
   id serial PRIMARY KEY,
   surveyDate DATE NOT NULL,
   schoolId INT NOT NULL,
   deliveredById INT NOT NULL,
   duration INT NOT NULL,
   briefSummary VARCHAR(50) NOT NULL,
   numOfNewTeachers INT NOT NULL,
   numOfNewStudents INT NOT NULL,
   numOfExistingTeachers INT NOT NULL,
   numOfExistingStudents INT NOT NULL,
   totalNumTablets INT NOT NULL,
   supportCategory VARCHAR(50) NOT NULL,
   supportType VARCHAR(50) NOT NULL,
   programmeInitiativeId INT NOT NULL,
   grades VARCHAR(255) NOT NULL,
   languagesTaught VARCHAR(255) NOT NULL,
   created_ById INT NOT NULL,
   created_At TIMESTAMP NOT NULL DEFAULT NOW(),
   FOREIGN KEY (deliveredById)
                             REFERENCES person (id),
   FOREIGN KEY (schoolId)
                             REFERENCES schoolstat (id),
   FOREIGN KEY (programmeInitiativeId)
                             REFERENCES initiative (id));

-- Mock Data - ensure 'person, schoolstat, initiative' databases exist

INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2016-12-19 11:22:31', 
                                15,1,
                                4.5, 
                                'Health Care',
                                7,348,
                                44, 
                                489, 
                                92, 
                                'LDA',
                                'Internal Work',
                                1,
                                '4&5',
                                'isiXhosa',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2019-04-23 00:22:51', 
                                17,1,
                                4.5, 
                                'Vusa Training',
                                3,151,
                                35, 
                                95, 
                                71, 
                                'Visual Basic',
                                'Internal Work',
                                1,
                                'R-1',
                                'isiXhosa',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2018-09-20 03:59:31', 
                                1,1,
                                2, 
                                'Miscellaneous',
                                13,269,
                                37, 
                                28, 
                                39, 
                                'Adult Education',
                                'Internal Work',
                                1,
                                'R-3',
                                'Afrikaans',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2019-08-18 09:23:29', 
                                8,1,
                                4.5, 
                                'Vusa Training',
                                57,270,
                                64, 
                                301, 
                                56, 
                                'Google Docs',
                                'Direct Work',
                                1,
                                '4&5',
                                'Xhosa',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2016-12-14 23:19:33', 
                                13,1,
                                1.5, 
                                'Finance',
                                73,173,
                                71, 
                                479, 
                                39, 
                                'Vector Illustration',
                                'Internal Work',
                                1,
                                'R-2',
                                'Afrikaans',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2021-12-15 16:57:54', 
                                8,1,
                                1.5, 
                                'Finance',
                                92,215,
                                80, 
                                816, 
                                76, 
                                'RNAi',
                                'Direct Work',
                                1,
                                'R-1',
                                'Afrikaans',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2016-11-10 03:08:44', 
                                2,1,
                                4.5, 
                                'Finance',
                                23,265,
                                47, 
                                107, 
                                100, 
                                'Twill',
                                'Internal Work',
                                1,
                                '4-7',
                                'isiZulu',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2022-04-04 14:23:06', 
                                6,1,
                                5, 
                                'Consumer Services',
                                99,148,
                                60, 
                                237, 
                                71, 
                                'SMO',
                                'Direct Work',
                                1,
                                '4-7',
                                'isiZulu',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2016-08-05 18:32:07', 
                                19,1,
                                3, 
                                'Consumer Non-Durables',
                                56,259,
                                81, 
                                154, 
                                13, 
                                'Digital Illustration',
                                'Internal Work',
                                1,
                                '4&5',
                                'isiXhosa',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2018-03-20 21:40:00', 
                                15,1,
                                6, 
                                'Vusa Training',
                                56,397,
                                52, 
                                183, 
                                26, 
                                'RMS',
                                'Direct Work',
                                1,
                                '4&5',
                                'Afrikaans',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2018-12-25 10:03:07', 
                                10,1,
                                2, 
                                'Finance',
                                70,35,
                                48, 
                                397, 
                                56, 
                                'Zsh',
                                'Internal Work',
                                1,
                                'R-2',
                                'Afrikaans',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2021-02-25 23:35:37', 
                                14,1,
                                4.5, 
                                'Consumer Non-Durables',
                                41,33,
                                60, 
                                707, 
                                95, 
                                'TSM Administration',
                                'Direct Work',
                                1,
                                'R-3',
                                'English',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2019-02-15 18:48:18', 
                                18,1,
                                3.5, 
                                'Vusa Training',
                                64,112,
                                75, 
                                533, 
                                34, 
                                'XStream',
                                'Direct Work',
                                1,
                                '4-7',
                                'isiZulu',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2019-02-24 11:57:56', 
                                2,1,
                                2.5, 
                                'Vusa Training',
                                68,395,
                                90, 
                                765, 
                                44, 
                                'D3.js',
                                'Direct Work',
                                1,
                                'R-1',
                                'isiZulu',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2017-03-26 21:48:18', 
                                20,1,
                                1, 
                                'Vusa Training',
                                88,353,
                                45, 
                                197, 
                                94, 
                                'ISO 27001',
                                'Internal Work',
                                1,
                                '4&5',
                                'isiZulu',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2019-04-06 21:39:31', 
                                12,1,
                                2, 
                                'Vusa Training',
                                14,172,
                                59, 
                                245, 
                                72, 
                                'Analog Circuit Design',
                                'Direct Work',
                                1,
                                '4-7',
                                'Afrikaans',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2020-04-10 05:29:46', 
                                20,1,
                                5.5, 
                                'Consumer Services',
                                37,12,
                                97, 
                                274, 
                                94, 
                                'Yeast two-hybrid',
                                'Internal Work',
                                1,
                                '4&5',
                                'Afrikaans',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2016-07-17 07:30:57', 
                                1,1,
                                5.5, 
                                'Consumer Services',
                                52,147,
                                44, 
                                432, 
                                59, 
                                'Web Typography',
                                'Direct Work',
                                1,
                                '4-7',
                                'isiXhosa',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2020-08-18 06:12:01', 
                                14,1,
                                3.5, 
                                'Public Utilities',
                                27,322,
                                6, 
                                163, 
                                53, 
                                'Type Rating',
                                'Direct Work',
                                1,
                                '4-7',
                                'isiXhosa',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2018-06-09 21:48:52', 
                                9,1,
                                3, 
                                'Capital Goods',
                                44,59,
                                28, 
                                256, 
                                48, 
                                'Bash',
                                'Direct Work',
                                1,
                                'R-2',
                                'Xhosa',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2022-03-21 12:21:43', 
                                18,1,
                                5.5, 
                                'Miscellaneous',
                                54,291,
                                84, 
                                177, 
                                58, 
                                'MDX',
                                'Internal Work',
                                1,
                                '4&5',
                                'Afrikaans',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2020-12-19 12:59:32', 
                                13,1,
                                2.5, 
                                'Consumer Non-Durables',
                                71,215,
                                98, 
                                584, 
                                76, 
                                'QAM',
                                'Internal Work',
                                1,
                                '4-7',
                                'Xhosa',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2022-04-29 01:59:16', 
                                13,1,
                                4, 
                                'Vusa Training',
                                65,304,
                                99, 
                                854, 
                                37, 
                                'Kitchen Remodeling',
                                'Direct Work',
                                1,
                                'R-3',
                                'English',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2017-09-13 08:45:06', 
                                12,1,
                                2, 
                                'Consumer Services',
                                27,36,
                                23, 
                                557, 
                                29, 
                                'GMDSS',
                                'Direct Work',
                                1,
                                '4&5',
                                'English',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2018-03-19 11:27:10', 
                                6,1,
                                2, 
                                'Finance',
                                53,80,
                                69, 
                                285, 
                                15, 
                                'DFR',
                                'Direct Work',
                                1,
                                'R-3',
                                'Xhosa',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2019-12-09 16:47:38', 
                                4,1,
                                4.5, 
                                'Consumer Non-Durables',
                                5,373,
                                68, 
                                422, 
                                28, 
                                'OA Framework',
                                'Internal Work',
                                1,
                                'R-3',
                                'Afrikaans',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2019-11-13 11:51:47', 
                                11,1,
                                4, 
                                'Vusa Training',
                                12,1,
                                44, 
                                396, 
                                83, 
                                'Egyptian Arabic',
                                'Internal Work',
                                1,
                                'R-2',
                                'Xhosa',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2021-05-09 08:00:10', 
                                18,1,
                                2.5, 
                                'Vusa Training',
                                5,238,
                                67, 
                                505, 
                                70, 
                                'JBoss Application Server',
                                'Internal Work',
                                1,
                                '4&5',
                                'English',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2019-03-23 14:52:25', 
                                3,1,
                                4.5, 
                                'Vusa Training',
                                72,233,
                                90, 
                                986, 
                                99, 
                                'Vaccines',
                                'Internal Work',
                                1,
                                'R-1',
                                'isiXhosa',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2022-06-05 16:44:52', 
                                5,1,
                                2.5, 
                                'Consumer Services',
                                20,399,
                                57, 
                                13, 
                                61, 
                                'Kronos',
                                'Internal Work',
                                1,
                                'R-2',
                                'Afrikaans',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2017-04-27 22:17:39', 
                                7,1,
                                1.5, 
                                'Energy',
                                24,6,
                                45, 
                                11, 
                                21, 
                                'High Yield Bonds',
                                'Internal Work',
                                1,
                                'R-1',
                                'Xhosa',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2019-10-18 06:47:10', 
                                18,1,
                                3, 
                                'Capital Goods',
                                50,358,
                                60, 
                                451, 
                                91, 
                                'Waterfront',
                                'Direct Work',
                                1,
                                '4&5',
                                'isiZulu',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2020-01-13 16:57:54', 
                                15,1,
                                3, 
                                'Vusa Training',
                                57,111,
                                56, 
                                132, 
                                69, 
                                'BOSIET',
                                'Direct Work',
                                1,
                                '4-7',
                                'English',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2021-03-09 15:17:09', 
                                3,1,
                                3.5, 
                                'Vusa Training',
                                15,56,
                                98, 
                                179, 
                                75, 
                                'XML Sitemaps',
                                'Internal Work',
                                1,
                                'R-3',
                                'isiZulu',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2021-12-07 21:54:23', 
                                9,1,
                                2.5, 
                                'Consumer Non-Durables',
                                35,241,
                                18, 
                                122, 
                                69, 
                                'LP',
                                'Direct Work',
                                1,
                                'R-2',
                                'isiXhosa',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2017-10-16 11:44:13', 
                                2,1,
                                2, 
                                'Consumer Services',
                                99,313,
                                56, 
                                507, 
                                44, 
                                'MRIS',
                                'Internal Work',
                                1,
                                '4-7',
                                'isiXhosa',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2017-05-20 05:26:02', 
                                15,1,
                                5, 
                                'Finance',
                                27,298,
                                26, 
                                576, 
                                23, 
                                'Epi Info',
                                'Direct Work',
                                1,
                                '4&5',
                                'Xhosa',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2019-05-16 16:08:55', 
                                7,1,
                                1, 
                                'Basic Industries',
                                47,160,
                                71, 
                                655, 
                                16, 
                                'UCSC Genome Browser',
                                'Internal Work',
                                1,
                                'R-2',
                                'Xhosa',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2017-11-30 09:17:57', 
                                11,1,
                                5.5, 
                                'Vusa Training',
                                77,26,
                                21, 
                                221, 
                                93, 
                                'RS Means',
                                'Internal Work',
                                1,
                                'R-2',
                                'Xhosa',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2017-06-10 15:08:18', 
                                20,1,
                                4, 
                                'Finance',
                                13,159,
                                2, 
                                109, 
                                85, 
                                'KOL Identification',
                                'Internal Work',
                                1,
                                'R-2',
                                'Afrikaans',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2017-01-24 08:56:40', 
                                12,1,
                                3, 
                                'Miscellaneous',
                                87,37,
                                2, 
                                354, 
                                75, 
                                'Customer Support',
                                'Internal Work',
                                1,
                                'R-1',
                                'English',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2022-06-03 12:40:18', 
                                18,1,
                                1.5, 
                                'Finance',
                                70,209,
                                52, 
                                134, 
                                62, 
                                'IEEE standards',
                                'Direct Work',
                                1,
                                'R-2',
                                'isiXhosa',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2020-08-20 06:07:10', 
                                5,1,
                                2, 
                                'Miscellaneous',
                                57,280,
                                26, 
                                537, 
                                69, 
                                'Kyphoplasty',
                                'Internal Work',
                                1,
                                'R-1',
                                'Afrikaans',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2018-01-30 12:20:47', 
                                16,1,
                                5.5, 
                                'Health Care',
                                20,99,
                                15, 
                                192, 
                                40, 
                                'Dynamic Speaker',
                                'Internal Work',
                                1,
                                '4&5',
                                'Xhosa',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2019-01-31 13:58:58', 
                                2,1,
                                5, 
                                'Consumer Services',
                                57,321,
                                51, 
                                258, 
                                24, 
                                'Title Searches',
                                'Internal Work',
                                1,
                                'R-3',
                                'isiZulu',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2017-07-27 02:26:31', 
                                12,1,
                                4, 
                                'Finance',
                                40,39,
                                2, 
                                109, 
                                45, 
                                'Blues',
                                'Direct Work',
                                1,
                                'R-3',
                                'English',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2021-05-21 04:07:27', 
                                17,1,
                                1, 
                                'Vusa Training',
                                35,387,
                                33, 
                                442, 
                                12, 
                                'Dreamweaver',
                                'Direct Work',
                                1,
                                'R-3',
                                'Afrikaans',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2020-10-30 21:06:02', 
                                5,1,
                                5.5, 
                                'Basic Industries',
                                20,100,
                                37, 
                                138, 
                                23, 
                                'FHA',
                                'Internal Work',
                                1,
                                'R-3',
                                'isiZulu',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2018-01-02 12:10:18', 
                                6,1,
                                3, 
                                'Vusa Training',
                                61,22,
                                98, 
                                250, 
                                52, 
                                'VC-1',
                                'Direct Work',
                                1,
                                'R-1',
                                'English',                                    
                                1);
INSERT INTO scheduletracker (surveyDate, 
                                          schoolId, deliveredById,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES ('2016-08-01 17:46:50', 
                                13,1,
                                3, 
                                'Health Care',
                                55,342,
                                21, 
                                321, 
                                21, 
                                'Eyelid Surgery',
                                'Direct Work',
                                1,
                                '4-7',
                                'Afrikaans',                                    
                                1);
