DROP TABLE IF EXISTS scheduletracker;
-- Create Schedule Tracker Table
CREATE TABLE scheduletracker (
   id serial PRIMARY KEY,
   schoolId INT NOT NULL,
   duration INT NOT NULL,
   briefSummary VARCHAR(50) NOT NULL,
   numOfNewTeachers INT NOT NULL,
   numOfNewStudents INT NOT NULL,
   numOfExistingTeachers INT NOT NULL,
   numOfExistingStudents INT NOT NULL,
   totalNumTablets INT NOT NULL,
   supportCategory VARCHAR(50) NOT NULL,
   supportType VARCHAR(50) NOT NULL,
   programmeInitiativeId INT NOT NULL,
   grades VARCHAR(255) NOT NULL,
   languagesTaught VARCHAR(255) NOT NULL,
   created_ById INT NOT NULL,
   created_At TIMESTAMP NOT NULL DEFAULT NOW(),
   FOREIGN KEY (created_ById)
                             REFERENCES person (id),
   FOREIGN KEY (schoolId)
                             REFERENCES schoolstat (id),
   FOREIGN KEY (programmeInitiativeId)
                             REFERENCES initiative (id));

-- Mock Data - ensure 'person, schoolstat, initiative' databases exist

INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (5,
                                4.5, 
                                'Health Care',
                                19,303,
                                44, 
                                489, 
                                92, 
                                'LDA',
                                'Internal Work',
                                1,
                                '4&5',
                                'isiXhosa',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (1,
                                4.5, 
                                'Vusa Training',
                                6,180,
                                35, 
                                95, 
                                71, 
                                'Visual Basic',
                                'Internal Work',
                                1,
                                'R-1',
                                'isiXhosa',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (6,
                                2, 
                                'Miscellaneous',
                                35,53,
                                37, 
                                28, 
                                39, 
                                'Adult Education',
                                'Internal Work',
                                1,
                                'R-3',
                                'Afrikaans',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (5,
                                4.5, 
                                'Vusa Training',
                                75,353,
                                64, 
                                301, 
                                56, 
                                'Google Docs',
                                'Direct Work',
                                1,
                                '4&5',
                                'Xhosa',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (7,
                                1.5, 
                                'Finance',
                                94,367,
                                71, 
                                479, 
                                39, 
                                'Vector Illustration',
                                'Internal Work',
                                1,
                                'R-2',
                                'Afrikaans',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (8,
                                1.5, 
                                'Finance',
                                30,128,
                                80, 
                                816, 
                                76, 
                                'RNAi',
                                'Direct Work',
                                1,
                                'R-1',
                                'Afrikaans',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (4,
                                4.5, 
                                'Finance',
                                89,294,
                                47, 
                                107, 
                                100, 
                                'Twill',
                                'Internal Work',
                                1,
                                '4-7',
                                'isiZulu',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (6,
                                5, 
                                'Consumer Services',
                                86,260,
                                60, 
                                237, 
                                71, 
                                'SMO',
                                'Direct Work',
                                1,
                                '4-7',
                                'isiZulu',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (12,
                                3, 
                                'Consumer Non-Durables',
                                88,93,
                                81, 
                                154, 
                                13, 
                                'Digital Illustration',
                                'Internal Work',
                                1,
                                '4&5',
                                'isiXhosa',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (17,
                                6, 
                                'Vusa Training',
                                82,258,
                                52, 
                                183, 
                                26, 
                                'RMS',
                                'Direct Work',
                                1,
                                '4&5',
                                'Afrikaans',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (12,
                                2, 
                                'Finance',
                                9,124,
                                48, 
                                397, 
                                56, 
                                'Zsh',
                                'Internal Work',
                                1,
                                'R-2',
                                'Afrikaans',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (1,
                                4.5, 
                                'Consumer Non-Durables',
                                38,79,
                                60, 
                                707, 
                                95, 
                                'TSM Administration',
                                'Direct Work',
                                1,
                                'R-3',
                                'English',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (18,
                                3.5, 
                                'Vusa Training',
                                15,159,
                                75, 
                                533, 
                                34, 
                                'XStream',
                                'Direct Work',
                                1,
                                '4-7',
                                'isiZulu',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (12,
                                2.5, 
                                'Vusa Training',
                                9,281,
                                90, 
                                765, 
                                44, 
                                'D3.js',
                                'Direct Work',
                                1,
                                'R-1',
                                'isiZulu',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (17,
                                1, 
                                'Vusa Training',
                                94,187,
                                45, 
                                197, 
                                94, 
                                'ISO 27001',
                                'Internal Work',
                                1,
                                '4&5',
                                'isiZulu',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (13,
                                2, 
                                'Vusa Training',
                                61,384,
                                59, 
                                245, 
                                72, 
                                'Analog Circuit Design',
                                'Direct Work',
                                1,
                                '4-7',
                                'Afrikaans',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (18,
                                5.5, 
                                'Consumer Services',
                                48,222,
                                97, 
                                274, 
                                94, 
                                'Yeast two-hybrid',
                                'Internal Work',
                                1,
                                '4&5',
                                'Afrikaans',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (5,
                                5.5, 
                                'Consumer Services',
                                84,41,
                                44, 
                                432, 
                                59, 
                                'Web Typography',
                                'Direct Work',
                                1,
                                '4-7',
                                'isiXhosa',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (15,
                                3.5, 
                                'Public Utilities',
                                67,144,
                                6, 
                                163, 
                                53, 
                                'Type Rating',
                                'Direct Work',
                                1,
                                '4-7',
                                'isiXhosa',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (7,
                                3, 
                                'Capital Goods',
                                60,255,
                                28, 
                                256, 
                                48, 
                                'Bash',
                                'Direct Work',
                                1,
                                'R-2',
                                'Xhosa',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (8,
                                5.5, 
                                'Miscellaneous',
                                91,197,
                                84, 
                                177, 
                                58, 
                                'MDX',
                                'Internal Work',
                                1,
                                '4&5',
                                'Afrikaans',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (6,
                                2.5, 
                                'Consumer Non-Durables',
                                93,309,
                                98, 
                                584, 
                                76, 
                                'QAM',
                                'Internal Work',
                                1,
                                '4-7',
                                'Xhosa',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (6,
                                4, 
                                'Vusa Training',
                                58,304,
                                99, 
                                854, 
                                37, 
                                'Kitchen Remodeling',
                                'Direct Work',
                                1,
                                'R-3',
                                'English',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (16,
                                2, 
                                'Consumer Services',
                                28,288,
                                23, 
                                557, 
                                29, 
                                'GMDSS',
                                'Direct Work',
                                1,
                                '4&5',
                                'English',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (10,
                                2, 
                                'Finance',
                                12,138,
                                69, 
                                285, 
                                15, 
                                'DFR',
                                'Direct Work',
                                1,
                                'R-3',
                                'Xhosa',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (10,
                                4.5, 
                                'Consumer Non-Durables',
                                97,73,
                                68, 
                                422, 
                                28, 
                                'OA Framework',
                                'Internal Work',
                                1,
                                'R-3',
                                'Afrikaans',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (3,
                                4, 
                                'Vusa Training',
                                21,18,
                                44, 
                                396, 
                                83, 
                                'Egyptian Arabic',
                                'Internal Work',
                                1,
                                'R-2',
                                'Xhosa',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (3,
                                2.5, 
                                'Vusa Training',
                                4,395,
                                67, 
                                505, 
                                70, 
                                'JBoss Application Server',
                                'Internal Work',
                                1,
                                '4&5',
                                'English',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (16,
                                4.5, 
                                'Vusa Training',
                                20,389,
                                90, 
                                986, 
                                99, 
                                'Vaccines',
                                'Internal Work',
                                1,
                                'R-1',
                                'isiXhosa',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (17,
                                2.5, 
                                'Consumer Services',
                                73,353,
                                57, 
                                13, 
                                61, 
                                'Kronos',
                                'Internal Work',
                                1,
                                'R-2',
                                'Afrikaans',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (1,
                                1.5, 
                                'Energy',
                                33,6,
                                45, 
                                11, 
                                21, 
                                'High Yield Bonds',
                                'Internal Work',
                                1,
                                'R-1',
                                'Xhosa',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (12,
                                3, 
                                'Capital Goods',
                                40,284,
                                60, 
                                451, 
                                91, 
                                'Waterfront',
                                'Direct Work',
                                1,
                                '4&5',
                                'isiZulu',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (2,
                                3, 
                                'Vusa Training',
                                48,387,
                                56, 
                                132, 
                                69, 
                                'BOSIET',
                                'Direct Work',
                                1,
                                '4-7',
                                'English',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (17,
                                3.5, 
                                'Vusa Training',
                                55,5,
                                98, 
                                179, 
                                75, 
                                'XML Sitemaps',
                                'Internal Work',
                                1,
                                'R-3',
                                'isiZulu',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (4,
                                2.5, 
                                'Consumer Non-Durables',
                                70,129,
                                18, 
                                122, 
                                69, 
                                'LP',
                                'Direct Work',
                                1,
                                'R-2',
                                'isiXhosa',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (9,
                                2, 
                                'Consumer Services',
                                72,375,
                                56, 
                                507, 
                                44, 
                                'MRIS',
                                'Internal Work',
                                1,
                                '4-7',
                                'isiXhosa',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (17,
                                5, 
                                'Finance',
                                57,207,
                                26, 
                                576, 
                                23, 
                                'Epi Info',
                                'Direct Work',
                                1,
                                '4&5',
                                'Xhosa',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (9,
                                1, 
                                'Basic Industries',
                                8,146,
                                71, 
                                655, 
                                16, 
                                'UCSC Genome Browser',
                                'Internal Work',
                                1,
                                'R-2',
                                'Xhosa',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (6,
                                5.5, 
                                'Vusa Training',
                                86,286,
                                21, 
                                221, 
                                93, 
                                'RS Means',
                                'Internal Work',
                                1,
                                'R-2',
                                'Xhosa',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (5,
                                4, 
                                'Finance',
                                40,54,
                                2, 
                                109, 
                                85, 
                                'KOL Identification',
                                'Internal Work',
                                1,
                                'R-2',
                                'Afrikaans',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (17,
                                3, 
                                'Miscellaneous',
                                53,52,
                                2, 
                                354, 
                                75, 
                                'Customer Support',
                                'Internal Work',
                                1,
                                'R-1',
                                'English',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (9,
                                1.5, 
                                'Finance',
                                73,392,
                                52, 
                                134, 
                                62, 
                                'IEEE standards',
                                'Direct Work',
                                1,
                                'R-2',
                                'isiXhosa',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (12,
                                2, 
                                'Miscellaneous',
                                34,111,
                                26, 
                                537, 
                                69, 
                                'Kyphoplasty',
                                'Internal Work',
                                1,
                                'R-1',
                                'Afrikaans',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (15,
                                5.5, 
                                'Health Care',
                                76,12,
                                15, 
                                192, 
                                40, 
                                'Dynamic Speaker',
                                'Internal Work',
                                1,
                                '4&5',
                                'Xhosa',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (16,
                                5, 
                                'Consumer Services',
                                50,346,
                                51, 
                                258, 
                                24, 
                                'Title Searches',
                                'Internal Work',
                                1,
                                'R-3',
                                'isiZulu',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (10,
                                4, 
                                'Finance',
                                55,29,
                                2, 
                                109, 
                                45, 
                                'Blues',
                                'Direct Work',
                                1,
                                'R-3',
                                'English',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (8,
                                1, 
                                'Vusa Training',
                                80,349,
                                33, 
                                442, 
                                12, 
                                'Dreamweaver',
                                'Direct Work',
                                1,
                                'R-3',
                                'Afrikaans',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (14,
                                5.5, 
                                'Basic Industries',
                                33,199,
                                37, 
                                138, 
                                23, 
                                'FHA',
                                'Internal Work',
                                1,
                                'R-3',
                                'isiZulu',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (13,
                                3, 
                                'Vusa Training',
                                12,316,
                                98, 
                                250, 
                                52, 
                                'VC-1',
                                'Direct Work',
                                1,
                                'R-1',
                                'English',                                    
                                1);
INSERT INTO scheduletracker (schoolId,
                                          duration, briefSummary, 
                                          numOfNewTeachers, numOfNewStudents,
                                          numOfExistingTeachers, numOfExistingStudents,
                                          totalNumTablets,
                                          supportCategory, supportType,   
                                          programmeInitiativeId,
                                          grades, languagesTaught,
                                          created_ById)
        VALUES (14,
                                3, 
                                'Health Care',
                                96,122,
                                21, 
                                321, 
                                21, 
                                'Eyelid Surgery',
                                'Direct Work',
                                1,
                                '4-7',
                                'Afrikaans',                                    
                                1);
