DROP TABLE IF EXISTS schoolstats;
-- Create School Stats Table
CREATE TABLE schoolstats (
   id serial PRIMARY KEY,
   schoolName VARCHAR(50) NOT NULL,
   location VARCHAR(50) NOT NULL,
   country VARCHAR(50) NOT NULL,
   responsibleId INT NOT NULL,
   status VARCHAR(50) NOT NULL,
   deploymentYear DATE NOT NULL,
   numStudentsReached INT NOT NULL,
   numTeachersReached INT NOT NULL,
   totalNumTablets INT NOT NULL,
   totalNumTeachers INT NOT NULL,
   tabletType VARCHAR(50) NOT NULL,
   numDoodleStudents INT NOT NULL,
   internetDetails VARCHAR(50) NOT NULL,
   totalSchools INT NOT NULL,
   deployment DATE NOT NULL,
   grades VARCHAR(50) NOT NULL,
   languagesTaught VARCHAR(50) NOT NULL,
   createdById INT NOT NULL,
   createdAt TIMESTAMP NOT NULL DEFAULT NOW(),
   updatedById INT NOT NULL,
   updatedAt TIMESTAMP NOT NULL DEFAULT NOW(),
   FOREIGN KEY (responsibleId)
                             REFERENCES users (id));

-- Mock Data - ensure 'users' database exist

INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Yundt LLC', 'Cape First', 
                                  'Indonesia',
                                  13, 'Autonomous', 
                                  '2020-09-04 20:38:22',
                                  489, 
                                  44,
                                  92, 
                                  83,
                                  'Lenovo',
                                  74,
                                  'Strong Wifi',
                                  5,
                                  '2019-10-06 09:27:02',
                                  '4&5',
                                  'isiXhosa',
                                  13,13);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Roob, Legros and Kozey', 'Gerald', 
                                  'Philippines',
                                  13, 'Autonomous', 
                                  '2018-04-24 04:09:39',
                                  95, 
                                  35,
                                  71, 
                                  20,
                                  'Lenovo',
                                  18,
                                  'None',
                                  6,
                                  '2021-03-01 19:41:23',
                                  'R-1',
                                  'isiXhosa',
                                  13,13);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Bins-Konopelski', 'Valley Edge', 
                                  'Philippines',
                                  20, 'Autonomous', 
                                  '2017-12-27 11:57:19',
                                  28, 
                                  37,
                                  39, 
                                  56,
                                  'Nexus',
                                  96,
                                  'Spotty Wifi',
                                  9,
                                  '2020-06-25 23:44:38',
                                  'R-3',
                                  'Afrikaans',
                                  20,20);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Hagenes, Bosco and Morar', 'Nova', 
                                  'Greece',
                                  18, 'Autonomous', 
                                  '2017-05-12 08:44:53',
                                  301, 
                                  64,
                                  56, 
                                  49,
                                  'Lenovo',
                                  51,
                                  'BF Router',
                                  10,
                                  '2018-03-14 08:32:27',
                                  '4&5',
                                  'Xhosa',
                                  18,18);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Bergnaum-Kuhn', 'Buell', 
                                  'China',
                                  1, 'Autonomous', 
                                  '2017-10-26 23:14:42',
                                  479, 
                                  71,
                                  39, 
                                  69,
                                  'Ipad',
                                  37,
                                  'WCED Wifi',
                                  6,
                                  '2022-03-11 18:45:49',
                                  'R-2',
                                  'Afrikaans',
                                  1,1);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Nicolas-Ferry', 'Westerfield', 
                                  'Ukraine',
                                  14, 'Autonomous', 
                                  '2017-10-23 02:54:48',
                                  816, 
                                  80,
                                  76, 
                                  3,
                                  'Ipad',
                                  72,
                                  'WCED Wifi',
                                  1,
                                  '2022-01-22 20:54:31',
                                  'R-1',
                                  'Afrikaans',
                                  14,14);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Connelly Inc', 'Gina', 
                                  'Sweden',
                                  12, 'Autonomous', 
                                  '2019-03-17 18:28:56',
                                  107, 
                                  47,
                                  100, 
                                  25,
                                  'Ipad',
                                  93,
                                  'Spotty Wifi',
                                  8,
                                  '2021-07-17 23:11:33',
                                  '4-7',
                                  'isiZulu',
                                  12,12);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Hermiston, Lockman and Rohan', 'Spenser', 
                                  'France',
                                  13, 'Autonomous', 
                                  '2021-04-20 23:17:20',
                                  237, 
                                  60,
                                  71, 
                                  8,
                                  'Lenovo',
                                  62,
                                  'None',
                                  10,
                                  '2019-06-01 04:41:24',
                                  '4-7',
                                  'isiZulu',
                                  13,13);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Kon, Conroy and Grant', 'Prairieview', 
                                  'Poland',
                                  7, 'Autonomous', 
                                  '2018-11-26 21:04:17',
                                  154, 
                                  81,
                                  13, 
                                  75,
                                  'Lenovo',
                                  10,
                                  'WCED Wifi',
                                  3,
                                  '2019-09-14 10:45:14',
                                  '4&5',
                                  'isiXhosa',
                                  7,7);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Gutmann Inc', 'Steensland', 
                                  'China',
                                  12, 'Autonomous', 
                                  '2021-11-15 10:47:03',
                                  183, 
                                  52,
                                  26, 
                                  76,
                                  'Lenovo',
                                  53,
                                  'Spotty Wifi',
                                  3,
                                  '2021-01-03 10:20:22',
                                  '4&5',
                                  'Afrikaans',
                                  12,12);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Schoen Inc', 'Vidon', 
                                  'Netherlands',
                                  16, 'Autonomous', 
                                  '2017-02-05 19:42:52',
                                  397, 
                                  48,
                                  56, 
                                  94,
                                  'Lenovo',
                                  3,
                                  'BF Router',
                                  10,
                                  '2021-06-25 00:02:09',
                                  'R-2',
                                  'Afrikaans',
                                  16,16);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Sanford Group', 'Lotheville', 
                                  'Albania',
                                  14, 'Autonomous', 
                                  '2021-12-22 16:04:55',
                                  707, 
                                  60,
                                  95, 
                                  95,
                                  'Ipad',
                                  36,
                                  'Strong Wifi',
                                  5,
                                  '2021-01-14 23:29:18',
                                  'R-3',
                                  'English',
                                  14,14);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Wyman-Boyle', 'Susan', 
                                  'Sweden',
                                  4, 'Autonomous', 
                                  '2019-07-29 18:15:36',
                                  533, 
                                  75,
                                  34, 
                                  58,
                                  'Nexus',
                                  37,
                                  'Strong Wifi',
                                  9,
                                  '2021-07-11 04:01:12',
                                  '4-7',
                                  'isiZulu',
                                  4,4);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Yundt-Abbott', 'Corben', 
                                  'Argentina',
                                  12, 'Autonomous', 
                                  '2021-07-30 13:56:05',
                                  765, 
                                  90,
                                  44, 
                                  48,
                                  'Nexus',
                                  24,
                                  'None',
                                  5,
                                  '2021-11-06 23:50:46',
                                  'R-1',
                                  'isiZulu',
                                  12,12);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Jenkins, Mante and Bartoletti', 'Kensington', 
                                  'Colombia',
                                  15, 'Autonomous', 
                                  '2017-08-12 00:48:46',
                                  197, 
                                  45,
                                  94, 
                                  34,
                                  'Nexus',
                                  70,
                                  'None',
                                  1,
                                  '2016-09-19 03:34:45',
                                  '4&5',
                                  'isiZulu',
                                  15,15);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Gutmann LLC', 'Hooker', 
                                  'Colombia',
                                  10, 'Autonomous', 
                                  '2018-05-22 01:13:29',
                                  245, 
                                  59,
                                  72, 
                                  73,
                                  'Nexus',
                                  0,
                                  'WCED Wifi',
                                  1,
                                  '2019-07-05 20:25:54',
                                  '4-7',
                                  'Afrikaans',
                                  10,10);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Auer-Legros', 'Anthes', 
                                  'New Zealand',
                                  9, 'Autonomous', 
                                  '2019-07-31 14:44:32',
                                  274, 
                                  97,
                                  94, 
                                  27,
                                  'Ipad',
                                  84,
                                  'Spotty Wifi',
                                  4,
                                  '2020-06-30 04:23:25',
                                  '4&5',
                                  'Afrikaans',
                                  9,9);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Medhurst-McLaughlin', 'Maywood', 
                                  'China',
                                  1, 'Autonomous', 
                                  '2022-04-25 13:55:12',
                                  432, 
                                  44,
                                  59, 
                                  39,
                                  'Lenovo',
                                  20,
                                  'BF Router',
                                  4,
                                  '2019-12-10 23:07:53',
                                  '4-7',
                                  'isiXhosa',
                                  1,1);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('McKenzie, Schmidt and Connell', 'Corry', 
                                  'Colombia',
                                  8, 'Autonomous', 
                                  '2021-06-18 14:09:51',
                                  163, 
                                  6,
                                  53, 
                                  41,
                                  'Nexus',
                                  8,
                                  'WCED Wifi',
                                  10,
                                  '2017-05-03 15:43:27',
                                  '4-7',
                                  'isiXhosa',
                                  8,8);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Blick, Sauer and Stamm', 'Stang', 
                                  'China',
                                  18, 'Autonomous', 
                                  '2019-06-28 16:22:52',
                                  256, 
                                  28,
                                  48, 
                                  19,
                                  'Nexus',
                                  60,
                                  'WCED Wifi',
                                  2,
                                  '2022-04-23 16:10:35',
                                  'R-2',
                                  'Xhosa',
                                  18,18);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Moen, Cummerata and Mayer', 'Moose', 
                                  'China',
                                  7, 'Autonomous', 
                                  '2019-11-15 10:12:23',
                                  177, 
                                  84,
                                  58, 
                                  93,
                                  'Ipad',
                                  13,
                                  'Spotty Wifi',
                                  5,
                                  '2018-12-01 05:04:54',
                                  '4&5',
                                  'Afrikaans',
                                  7,7);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Kub LLC', 'Stuart', 
                                  'Philippines',
                                  4, 'Autonomous', 
                                  '2019-07-10 00:58:29',
                                  584, 
                                  98,
                                  76, 
                                  41,
                                  'Lenovo',
                                  56,
                                  'WCED Wifi',
                                  5,
                                  '2019-04-28 06:52:46',
                                  '4-7',
                                  'Xhosa',
                                  4,4);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Konopelski-Beer', 'Donald', 
                                  'China',
                                  3, 'Autonomous', 
                                  '2021-12-04 03:56:53',
                                  854, 
                                  99,
                                  37, 
                                  26,
                                  'Lenovo',
                                  84,
                                  'Strong Wifi',
                                  1,
                                  '2021-04-03 03:21:00',
                                  'R-3',
                                  'English',
                                  3,3);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Wiza, Ziemann and Kon', 'Sycamore', 
                                  'Portugal',
                                  10, 'Autonomous', 
                                  '2018-10-09 04:17:18',
                                  557, 
                                  23,
                                  29, 
                                  42,
                                  'Lenovo',
                                  78,
                                  'Strong Wifi',
                                  5,
                                  '2021-08-12 15:30:37',
                                  '4&5',
                                  'English',
                                  10,10);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Hansen, Hane and Bayer', 'Dayton', 
                                  'Democratic Republic of the Congo',
                                  4, 'Autonomous', 
                                  '2017-11-18 04:55:14',
                                  285, 
                                  69,
                                  15, 
                                  84,
                                  'Nexus',
                                  45,
                                  'Strong Wifi',
                                  9,
                                  '2016-11-11 18:19:14',
                                  'R-3',
                                  'Xhosa',
                                  4,4);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Hudson and Sons', 'Upham', 
                                  'Russia',
                                  5, 'Autonomous', 
                                  '2018-02-11 01:41:22',
                                  422, 
                                  68,
                                  28, 
                                  13,
                                  'Ipad',
                                  10,
                                  'Strong Wifi',
                                  6,
                                  '2016-07-13 21:20:05',
                                  'R-3',
                                  'Afrikaans',
                                  5,5);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Moore Group', 'Carpenter', 
                                  'China',
                                  18, 'Autonomous', 
                                  '2018-09-27 02:16:08',
                                  396, 
                                  44,
                                  83, 
                                  69,
                                  'Nexus',
                                  79,
                                  'Spotty Wifi',
                                  5,
                                  '2019-01-15 05:41:15',
                                  'R-2',
                                  'Xhosa',
                                  18,18);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Turcotte, Pfeffer and Feeney', 'Sage', 
                                  'Myanmar',
                                  4, 'Autonomous', 
                                  '2019-10-14 16:33:45',
                                  505, 
                                  67,
                                  70, 
                                  12,
                                  'Lenovo',
                                  17,
                                  'Spotty Wifi',
                                  5,
                                  '2016-08-22 22:34:31',
                                  '4&5',
                                  'English',
                                  4,4);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Boyer-Runte', 'Haas', 
                                  'China',
                                  10, 'Autonomous', 
                                  '2020-03-14 19:07:10',
                                  986, 
                                  90,
                                  99, 
                                  6,
                                  'Ipad',
                                  84,
                                  'Strong Wifi',
                                  5,
                                  '2019-07-19 06:42:04',
                                  'R-1',
                                  'isiXhosa',
                                  10,10);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Kozey, Mueller and Kerluke', 'Ronald Regan', 
                                  'Japan',
                                  19, 'Autonomous', 
                                  '2020-12-26 21:08:16',
                                  13, 
                                  57,
                                  61, 
                                  40,
                                  'Ipad',
                                  48,
                                  'Spotty Wifi',
                                  3,
                                  '2019-09-18 23:46:23',
                                  'R-2',
                                  'Afrikaans',
                                  19,19);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Schultz-Witting', 'Pierstorff', 
                                  'China',
                                  10, 'Autonomous', 
                                  '2016-11-20 18:56:21',
                                  11, 
                                  45,
                                  21, 
                                  26,
                                  'Lenovo',
                                  23,
                                  'WCED Wifi',
                                  3,
                                  '2017-01-21 10:21:22',
                                  'R-1',
                                  'Xhosa',
                                  10,10);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Hilll-Mohr', 'Bluejay', 
                                  'Greece',
                                  12, 'Autonomous', 
                                  '2017-12-30 17:31:53',
                                  451, 
                                  60,
                                  91, 
                                  18,
                                  'Nexus',
                                  45,
                                  'WCED Wifi',
                                  6,
                                  '2021-11-26 07:03:27',
                                  '4&5',
                                  'isiZulu',
                                  12,12);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Howe Inc', 'Bashford', 
                                  'Indonesia',
                                  10, 'Autonomous', 
                                  '2019-02-25 20:44:25',
                                  132, 
                                  56,
                                  69, 
                                  28,
                                  'Nexus',
                                  94,
                                  'Strong Wifi',
                                  6,
                                  '2020-12-03 15:10:38',
                                  '4-7',
                                  'English',
                                  10,10);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Berge, Treutel and Schmidt', 'Doe Crossing', 
                                  'Russia',
                                  9, 'Autonomous', 
                                  '2017-02-21 12:27:37',
                                  179, 
                                  98,
                                  75, 
                                  11,
                                  'Nexus',
                                  38,
                                  'Strong Wifi',
                                  10,
                                  '2021-12-30 06:17:37',
                                  'R-3',
                                  'isiZulu',
                                  9,9);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Price, Lakin and Streich', 'Clove', 
                                  'Brazil',
                                  2, 'Autonomous', 
                                  '2019-05-27 02:53:04',
                                  122, 
                                  18,
                                  69, 
                                  52,
                                  'Lenovo',
                                  72,
                                  'WCED Wifi',
                                  6,
                                  '2019-06-13 01:05:35',
                                  'R-2',
                                  'isiXhosa',
                                  2,2);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Veum-Heathcote', 'Monument', 
                                  'Poland',
                                  19, 'Autonomous', 
                                  '2019-11-29 05:14:42',
                                  507, 
                                  56,
                                  44, 
                                  77,
                                  'Ipad',
                                  87,
                                  'Spotty Wifi',
                                  5,
                                  '2018-09-23 01:54:08',
                                  '4-7',
                                  'isiXhosa',
                                  19,19);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Weimann Group', 'Burning Wood', 
                                  'Bulgaria',
                                  12, 'Autonomous', 
                                  '2020-04-07 10:28:50',
                                  576, 
                                  26,
                                  23, 
                                  41,
                                  'Nexus',
                                  24,
                                  'WCED Wifi',
                                  6,
                                  '2017-02-04 13:57:33',
                                  '4&5',
                                  'Xhosa',
                                  12,12);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Monahan, Witting and Keefe', 'Forest Run', 
                                  'France',
                                  8, 'Autonomous', 
                                  '2017-03-24 01:18:24',
                                  655, 
                                  71,
                                  16, 
                                  25,
                                  'Lenovo',
                                  13,
                                  'Strong Wifi',
                                  9,
                                  '2017-09-16 12:19:31',
                                  'R-2',
                                  'Xhosa',
                                  8,8);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Rowe-McClure', 'Union', 
                                  'Czech Republic',
                                  4, 'Autonomous', 
                                  '2021-03-09 02:02:45',
                                  221, 
                                  21,
                                  93, 
                                  20,
                                  'Ipad',
                                  41,
                                  'None',
                                  1,
                                  '2017-04-01 16:24:35',
                                  'R-2',
                                  'Xhosa',
                                  4,4);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Hermann, Gislason and Carroll', 'Shoshone', 
                                  'Nigeria',
                                  12, 'Autonomous', 
                                  '2017-06-03 16:28:46',
                                  109, 
                                  2,
                                  85, 
                                  66,
                                  'Ipad',
                                  23,
                                  'WCED Wifi',
                                  9,
                                  '2021-05-06 15:37:52',
                                  'R-2',
                                  'Afrikaans',
                                  12,12);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Jast and Sons', 'Hagan', 
                                  'Sri Lanka',
                                  10, 'Autonomous', 
                                  '2020-11-18 06:33:45',
                                  354, 
                                  2,
                                  75, 
                                  16,
                                  'Ipad',
                                  78,
                                  'Strong Wifi',
                                  7,
                                  '2019-10-24 23:09:21',
                                  'R-1',
                                  'English',
                                  10,10);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Nitzsche, Mertz and West', 'Arrowood', 
                                  'Australia',
                                  15, 'Autonomous', 
                                  '2019-12-29 16:19:45',
                                  134, 
                                  52,
                                  62, 
                                  8,
                                  'Lenovo',
                                  9,
                                  'Spotty Wifi',
                                  9,
                                  '2022-06-16 09:04:07',
                                  'R-2',
                                  'isiXhosa',
                                  15,15);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Towne, Schaden and Ankunding', 'Golden Leaf', 
                                  'China',
                                  20, 'Autonomous', 
                                  '2019-11-15 11:47:35',
                                  537, 
                                  26,
                                  69, 
                                  61,
                                  'Lenovo',
                                  8,
                                  'WCED Wifi',
                                  4,
                                  '2018-02-24 20:07:14',
                                  'R-1',
                                  'Afrikaans',
                                  20,20);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Schulist Group', 'Steensland', 
                                  'China',
                                  15, 'Autonomous', 
                                  '2020-05-30 22:26:19',
                                  192, 
                                  15,
                                  40, 
                                  48,
                                  'Nexus',
                                  42,
                                  'Spotty Wifi',
                                  7,
                                  '2021-12-06 01:18:25',
                                  '4&5',
                                  'Xhosa',
                                  15,15);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Stroman Inc', 'Heath', 
                                  'China',
                                  19, 'Autonomous', 
                                  '2017-08-25 01:13:36',
                                  258, 
                                  51,
                                  24, 
                                  69,
                                  'Nexus',
                                  5,
                                  'None',
                                  6,
                                  '2020-04-05 12:45:53',
                                  'R-3',
                                  'isiZulu',
                                  19,19);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Heathcote Inc', 'Tennyson', 
                                  'Greece',
                                  6, 'Autonomous', 
                                  '2021-07-02 12:27:10',
                                  109, 
                                  2,
                                  45, 
                                  40,
                                  'Lenovo',
                                  96,
                                  'WCED Wifi',
                                  10,
                                  '2019-05-15 22:18:02',
                                  'R-3',
                                  'English',
                                  6,6);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Kon-Lakin', 'Waubesa', 
                                  'Ecuador',
                                  14, 'Autonomous', 
                                  '2021-05-24 09:12:01',
                                  442, 
                                  33,
                                  12, 
                                  63,
                                  'Ipad',
                                  36,
                                  'None',
                                  6,
                                  '2017-02-17 14:47:58',
                                  'R-3',
                                  'Afrikaans',
                                  14,14);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Schiller-Graham', 'Kingsford', 
                                  'Japan',
                                  1, 'Autonomous', 
                                  '2020-01-20 10:16:46',
                                  138, 
                                  37,
                                  23, 
                                  72,
                                  'Nexus',
                                  90,
                                  'WCED Wifi',
                                  9,
                                  '2018-09-27 11:19:49',
                                  'R-3',
                                  'isiZulu',
                                  1,1);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Stoltenberg, Feest and Renner', 'Pine View', 
                                  'Argentina',
                                  16, 'Autonomous', 
                                  '2018-08-17 06:08:36',
                                  250, 
                                  98,
                                  52, 
                                  49,
                                  'Nexus',
                                  48,
                                  'BF Router',
                                  1,
                                  '2022-02-01 22:03:35',
                                  'R-1',
                                  'English',
                                  16,16);
INSERT INTO schoolstats (schoolName, location, country,
                                  responsibleId, status, deploymentYear,
                                  numStudentsReached, numTeachersReached,
                                  totalNumTablets, totalNumTeachers,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools, deployment, grades,
                                  languagesTaught,
                                  createdById, updatedById)
        VALUES ('Hauck-Stracke', 'American Ash', 
                                  'Indonesia',
                                  4, 'Autonomous', 
                                  '2018-09-27 19:03:56',
                                  321, 
                                  21,
                                  21, 
                                  57,
                                  'Ipad',
                                  54,
                                  'None',
                                  7,
                                  '2021-06-09 05:36:12',
                                  '4-7',
                                  'Afrikaans',
                                  4,4);
