DROP TABLE IF EXISTS schoolstat CASCADE;
-- Create School Stat Table
-- Assume Person '1' did all the entries
CREATE TABLE schoolstat (
   id serial PRIMARY KEY,
   name VARCHAR(50) NOT NULL,
   location VARCHAR(50) NOT NULL,
   country VARCHAR(50) NOT NULL,
   responsibleId INT NOT NULL,
   status VARCHAR(50) NOT NULL,
   deploymentDate DATE NOT NULL,
   tabletType VARCHAR(50),
   numDoodleStudents INT,
   internetDetails VARCHAR(50),
   totalSchools INT,
   created_ById INT NOT NULL,
   created_At TIMESTAMP NOT NULL DEFAULT NOW(),
   FOREIGN KEY (created_ById)
                             REFERENCES person (id));

-- Mock Data - ensure 'person' database exist

INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Yundt LLC', 'Cape First', 
                                  'Indonesia',
                                  1, 'Autonomous', 
                                  '2020-09-04 20:38:22',
                                  'Lenovo',
                                  74,
                                  'Strong Wifi',
                                  5,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Roob, Legros and Kozey', 'Gerald', 
                                  'Philippines',
                                  1, 'Autonomous', 
                                  '2018-04-24 04:09:39',
                                  'Lenovo',
                                  18,
                                  'None',
                                  6,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Bins-Konopelski', 'Valley Edge', 
                                  'Philippines',
                                  1, 'Autonomous', 
                                  '2017-12-27 11:57:19',
                                  'Nexus',
                                  96,
                                  'Spotty Wifi',
                                  9,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Hagenes, Bosco and Morar', 'Nova', 
                                  'Greece',
                                  1, 'Autonomous', 
                                  '2017-05-12 08:44:53',
                                  'Lenovo',
                                  51,
                                  'BF Router',
                                  10,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Bergnaum-Kuhn', 'Buell', 
                                  'China',
                                  1, 'Autonomous', 
                                  '2017-10-26 23:14:42',
                                  'Ipad',
                                  37,
                                  'WCED Wifi',
                                  6,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Nicolas-Ferry', 'Westerfield', 
                                  'Ukraine',
                                  1, 'Autonomous', 
                                  '2017-10-23 02:54:48',
                                  'Ipad',
                                  72,
                                  'WCED Wifi',
                                  1,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Connelly Inc', 'Gina', 
                                  'Sweden',
                                  1, 'Autonomous', 
                                  '2019-03-17 18:28:56',
                                  'Ipad',
                                  93,
                                  'Spotty Wifi',
                                  8,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Hermiston, Lockman and Rohan', 'Spenser', 
                                  'France',
                                  1, 'Autonomous', 
                                  '2021-04-20 23:17:20',
                                  'Lenovo',
                                  62,
                                  'None',
                                  10,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Kon, Conroy and Grant', 'Prairieview', 
                                  'Poland',
                                  1, 'Autonomous', 
                                  '2018-11-26 21:04:17',
                                  'Lenovo',
                                  10,
                                  'WCED Wifi',
                                  3,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Gutmann Inc', 'Steensland', 
                                  'China',
                                  1, 'Autonomous', 
                                  '2021-11-15 10:47:03',
                                  'Lenovo',
                                  53,
                                  'Spotty Wifi',
                                  3,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Schoen Inc', 'Vidon', 
                                  'Netherlands',
                                  1, 'Autonomous', 
                                  '2017-02-05 19:42:52',
                                  'Lenovo',
                                  3,
                                  'BF Router',
                                  10,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Sanford Group', 'Lotheville', 
                                  'Albania',
                                  1, 'Autonomous', 
                                  '2021-12-22 16:04:55',
                                  'Ipad',
                                  36,
                                  'Strong Wifi',
                                  5,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Wyman-Boyle', 'Susan', 
                                  'Sweden',
                                  1, 'Autonomous', 
                                  '2019-07-29 18:15:36',
                                  'Nexus',
                                  37,
                                  'Strong Wifi',
                                  9,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Yundt-Abbott', 'Corben', 
                                  'Argentina',
                                  1, 'Autonomous', 
                                  '2021-07-30 13:56:05',
                                  'Nexus',
                                  24,
                                  'None',
                                  5,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Jenkins, Mante and Bartoletti', 'Kensington', 
                                  'Colombia',
                                  1, 'Autonomous', 
                                  '2017-08-12 00:48:46',
                                  'Nexus',
                                  70,
                                  'None',
                                  1,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Gutmann LLC', 'Hooker', 
                                  'Colombia',
                                  1, 'Autonomous', 
                                  '2018-05-22 01:13:29',
                                  'Nexus',
                                  0,
                                  'WCED Wifi',
                                  1,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Auer-Legros', 'Anthes', 
                                  'New Zealand',
                                  1, 'Autonomous', 
                                  '2019-07-31 14:44:32',
                                  'Ipad',
                                  84,
                                  'Spotty Wifi',
                                  4,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Medhurst-McLaughlin', 'Maywood', 
                                  'China',
                                  1, 'Autonomous', 
                                  '2022-04-25 13:55:12',
                                  'Lenovo',
                                  20,
                                  'BF Router',
                                  4,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('McKenzie, Schmidt and Connell', 'Corry', 
                                  'Colombia',
                                  1, 'Autonomous', 
                                  '2021-06-18 14:09:51',
                                  'Nexus',
                                  8,
                                  'WCED Wifi',
                                  10,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Blick, Sauer and Stamm', 'Stang', 
                                  'China',
                                  1, 'Autonomous', 
                                  '2019-06-28 16:22:52',
                                  'Nexus',
                                  60,
                                  'WCED Wifi',
                                  2,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Moen, Cummerata and Mayer', 'Moose', 
                                  'China',
                                  1, 'Autonomous', 
                                  '2019-11-15 10:12:23',
                                  'Ipad',
                                  13,
                                  'Spotty Wifi',
                                  5,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Kub LLC', 'Stuart', 
                                  'Philippines',
                                  1, 'Autonomous', 
                                  '2019-07-10 00:58:29',
                                  'Lenovo',
                                  56,
                                  'WCED Wifi',
                                  5,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Konopelski-Beer', 'Donald', 
                                  'China',
                                  1, 'Autonomous', 
                                  '2021-12-04 03:56:53',
                                  'Lenovo',
                                  84,
                                  'Strong Wifi',
                                  1,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Wiza, Ziemann and Kon', 'Sycamore', 
                                  'Portugal',
                                  1, 'Autonomous', 
                                  '2018-10-09 04:17:18',
                                  'Lenovo',
                                  78,
                                  'Strong Wifi',
                                  5,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Hansen, Hane and Bayer', 'Dayton', 
                                  'Democratic Republic of the Congo',
                                  1, 'Autonomous', 
                                  '2017-11-18 04:55:14',
                                  'Nexus',
                                  45,
                                  'Strong Wifi',
                                  9,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Hudson and Sons', 'Upham', 
                                  'Russia',
                                  1, 'Autonomous', 
                                  '2018-02-11 01:41:22',
                                  'Ipad',
                                  10,
                                  'Strong Wifi',
                                  6,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Moore Group', 'Carpenter', 
                                  'China',
                                  1, 'Autonomous', 
                                  '2018-09-27 02:16:08',
                                  'Nexus',
                                  79,
                                  'Spotty Wifi',
                                  5,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Turcotte, Pfeffer and Feeney', 'Sage', 
                                  'Myanmar',
                                  1, 'Autonomous', 
                                  '2019-10-14 16:33:45',
                                  'Lenovo',
                                  17,
                                  'Spotty Wifi',
                                  5,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Boyer-Runte', 'Haas', 
                                  'China',
                                  1, 'Autonomous', 
                                  '2020-03-14 19:07:10',
                                  'Ipad',
                                  84,
                                  'Strong Wifi',
                                  5,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Kozey, Mueller and Kerluke', 'Ronald Regan', 
                                  'Japan',
                                  1, 'Autonomous', 
                                  '2020-12-26 21:08:16',
                                  'Ipad',
                                  48,
                                  'Spotty Wifi',
                                  3,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Schultz-Witting', 'Pierstorff', 
                                  'China',
                                  1, 'Autonomous', 
                                  '2016-11-20 18:56:21',
                                  'Lenovo',
                                  23,
                                  'WCED Wifi',
                                  3,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Hilll-Mohr', 'Bluejay', 
                                  'Greece',
                                  1, 'Autonomous', 
                                  '2017-12-30 17:31:53',
                                  'Nexus',
                                  45,
                                  'WCED Wifi',
                                  6,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Howe Inc', 'Bashford', 
                                  'Indonesia',
                                  1, 'Autonomous', 
                                  '2019-02-25 20:44:25',
                                  'Nexus',
                                  94,
                                  'Strong Wifi',
                                  6,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Berge, Treutel and Schmidt', 'Doe Crossing', 
                                  'Russia',
                                  1, 'Autonomous', 
                                  '2017-02-21 12:27:37',
                                  'Nexus',
                                  38,
                                  'Strong Wifi',
                                  10,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Price, Lakin and Streich', 'Clove', 
                                  'Brazil',
                                  1, 'Autonomous', 
                                  '2019-05-27 02:53:04',
                                  'Lenovo',
                                  72,
                                  'WCED Wifi',
                                  6,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Veum-Heathcote', 'Monument', 
                                  'Poland',
                                  1, 'Autonomous', 
                                  '2019-11-29 05:14:42',
                                  'Ipad',
                                  87,
                                  'Spotty Wifi',
                                  5,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Weimann Group', 'Burning Wood', 
                                  'Bulgaria',
                                  1, 'Autonomous', 
                                  '2020-04-07 10:28:50',
                                  'Nexus',
                                  24,
                                  'WCED Wifi',
                                  6,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Monahan, Witting and Keefe', 'Forest Run', 
                                  'France',
                                  1, 'Autonomous', 
                                  '2017-03-24 01:18:24',
                                  'Lenovo',
                                  13,
                                  'Strong Wifi',
                                  9,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Rowe-McClure', 'Union', 
                                  'Czech Republic',
                                  1, 'Autonomous', 
                                  '2021-03-09 02:02:45',
                                  'Ipad',
                                  41,
                                  'None',
                                  1,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Hermann, Gislason and Carroll', 'Shoshone', 
                                  'Nigeria',
                                  1, 'Autonomous', 
                                  '2017-06-03 16:28:46',
                                  'Ipad',
                                  23,
                                  'WCED Wifi',
                                  9,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Jast and Sons', 'Hagan', 
                                  'Sri Lanka',
                                  1, 'Autonomous', 
                                  '2020-11-18 06:33:45',
                                  'Ipad',
                                  78,
                                  'Strong Wifi',
                                  7,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Nitzsche, Mertz and West', 'Arrowood', 
                                  'Australia',
                                  1, 'Autonomous', 
                                  '2019-12-29 16:19:45',
                                  'Lenovo',
                                  9,
                                  'Spotty Wifi',
                                  9,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Towne, Schaden and Ankunding', 'Golden Leaf', 
                                  'China',
                                  1, 'Autonomous', 
                                  '2019-11-15 11:47:35',
                                  'Lenovo',
                                  8,
                                  'WCED Wifi',
                                  4,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Schulist Group', 'Steensland', 
                                  'China',
                                  1, 'Autonomous', 
                                  '2020-05-30 22:26:19',
                                  'Nexus',
                                  42,
                                  'Spotty Wifi',
                                  7,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Stroman Inc', 'Heath', 
                                  'China',
                                  1, 'Autonomous', 
                                  '2017-08-25 01:13:36',
                                  'Nexus',
                                  5,
                                  'None',
                                  6,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Heathcote Inc', 'Tennyson', 
                                  'Greece',
                                  1, 'Autonomous', 
                                  '2021-07-02 12:27:10',
                                  'Lenovo',
                                  96,
                                  'WCED Wifi',
                                  10,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Kon-Lakin', 'Waubesa', 
                                  'Ecuador',
                                  1, 'Autonomous', 
                                  '2021-05-24 09:12:01',
                                  'Ipad',
                                  36,
                                  'None',
                                  6,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Schiller-Graham', 'Kingsford', 
                                  'Japan',
                                  1, 'Autonomous', 
                                  '2020-01-20 10:16:46',
                                  'Nexus',
                                  90,
                                  'WCED Wifi',
                                  9,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Stoltenberg, Feest and Renner', 'Pine View', 
                                  'Argentina',
                                  1, 'Autonomous', 
                                  '2018-08-17 06:08:36',
                                  'Nexus',
                                  48,
                                  'BF Router',
                                  1,
                                  1);
INSERT INTO schoolstat (name, location, country,
                                  responsibleId, status, deploymentDate,
                                  tabletType, numDoodleStudents, internetDetails,
                                  totalSchools,
                                  created_ById)
        VALUES ('Hauck-Stracke', 'American Ash', 
                                  'Indonesia',
                                  1, 'Autonomous', 
                                  '2018-09-27 19:03:56',
                                  'Ipad',
                                  54,
                                  'None',
                                  7,
                                  1);
